# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalysisSettingsUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(287, 317)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Window.sizePolicy().hasHeightForWidth())
        Window.setSizePolicy(sizePolicy)
        Window.setMinimumSize(QtCore.QSize(287, 317))
        Window.setMaximumSize(QtCore.QSize(287, 317))
        Window.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Window)
        self.verticalLayout.setContentsMargins(20, 15, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_ThresholdSettings = QtWidgets.QLabel(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ThresholdSettings.sizePolicy().hasHeightForWidth())
        self.label_ThresholdSettings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_ThresholdSettings.setFont(font)
        self.label_ThresholdSettings.setWhatsThis("")
        self.label_ThresholdSettings.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_ThresholdSettings.setObjectName("label_ThresholdSettings")
        self.verticalLayout.addWidget(self.label_ThresholdSettings)
        self.formLayout_Threshold = QtWidgets.QFormLayout()
        self.formLayout_Threshold.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_Threshold.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_Threshold.setContentsMargins(10, -1, -1, 10)
        self.formLayout_Threshold.setHorizontalSpacing(20)
        self.formLayout_Threshold.setVerticalSpacing(15)
        self.formLayout_Threshold.setObjectName("formLayout_Threshold")
        self.label_StdDev = QtWidgets.QLabel(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_StdDev.sizePolicy().hasHeightForWidth())
        self.label_StdDev.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_StdDev.setFont(font)
        self.label_StdDev.setMouseTracking(False)
        self.label_StdDev.setWordWrap(False)
        self.label_StdDev.setObjectName("label_StdDev")
        self.formLayout_Threshold.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_StdDev)
        self.label_MinSamp = QtWidgets.QLabel(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MinSamp.sizePolicy().hasHeightForWidth())
        self.label_MinSamp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_MinSamp.setFont(font)
        self.label_MinSamp.setStatusTip("")
        self.label_MinSamp.setWordWrap(True)
        self.label_MinSamp.setObjectName("label_MinSamp")
        self.formLayout_Threshold.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_MinSamp)
        self.spinBox_2 = QtWidgets.QSpinBox(Window)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(300)
        self.spinBox_2.setSingleStep(1)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_Threshold.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.spinBox = QtWidgets.QSpinBox(Window)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBox.setFont(font)
        self.spinBox.setMouseTracking(True)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(20)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_Threshold.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.verticalLayout.addLayout(self.formLayout_Threshold)
        self.label_FileSettings = QtWidgets.QLabel(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_FileSettings.sizePolicy().hasHeightForWidth())
        self.label_FileSettings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_FileSettings.setFont(font)
        self.label_FileSettings.setObjectName("label_FileSettings")
        self.verticalLayout.addWidget(self.label_FileSettings)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(10, -1, -1, 10)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Overwrite = QtWidgets.QLabel(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Overwrite.sizePolicy().hasHeightForWidth())
        self.label_Overwrite.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Overwrite.setFont(font)
        self.label_Overwrite.setWordWrap(True)
        self.label_Overwrite.setObjectName("label_Overwrite")
        self.gridLayout_2.addWidget(self.label_Overwrite, 0, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(Window)
        self.radioButton.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton.setFont(font)
        self.radioButton.setText("")
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 0, 1, 1, 1)
        self.label_GenerateNew = QtWidgets.QLabel(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_GenerateNew.sizePolicy().hasHeightForWidth())
        self.label_GenerateNew.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_GenerateNew.setFont(font)
        self.label_GenerateNew.setWordWrap(True)
        self.label_GenerateNew.setObjectName("label_GenerateNew")
        self.gridLayout_2.addWidget(self.label_GenerateNew, 1, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(Window)
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 1, 1, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(0, 150)
        self.gridLayout_2.setColumnMinimumWidth(1, 15)
        self.gridLayout_2.setColumnStretch(0, 5)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(Window)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ReAnalyze = QtWidgets.QPushButton(Window)
        self.pushButton_ReAnalyze.setObjectName("pushButton_ReAnalyze")
        self.horizontalLayout.addWidget(self.pushButton_ReAnalyze)
        self.pushButton_Cancel = QtWidgets.QPushButton(Window)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout.addWidget(self.pushButton_Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 3)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)

        self.retranslateUi(Window)
        self.pushButton_Cancel.released.connect(Window.reject)
        self.pushButton_ReAnalyze.released.connect(Window.accept)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Dialog"))
        self.label_ThresholdSettings.setText(_translate("Window", "Threshold Settings"))
        self.label_StdDev.setToolTip(_translate("Window", "How many standard deviations the threshold is away from the average"))
        self.label_StdDev.setWhatsThis(_translate("Window", "<html><head/><body><p><span style=\" font-size:12pt;\">The number of standard deviations away from the average that the sample must be in order to be above the eyeblink threshold</span></p></body></html>"))
        self.label_StdDev.setText(_translate("Window", "Standard Deviations"))
        self.label_MinSamp.setToolTip(_translate("Window", "Number of consecutive samples above the threshold needed to count as an eyeblink"))
        self.label_MinSamp.setWhatsThis(_translate("Window", "<html><head/><body><p><span style=\" font-size:12pt;\">The minimum number of consecuitve samples that must be above the threshold in order to register as an eyeblink onset.</span></p><p><span style=\" font-size:12pt;\">Higher values make the analysis less susceptible to noise</span></p></body></html>"))
        self.label_MinSamp.setText(_translate("Window", "Minimum Samples Required"))
        self.spinBox_2.setToolTip(_translate("Window", "Number of consecutive samples above the threshold needed to count as an eyeblink"))
        self.spinBox_2.setWhatsThis(_translate("Window", "<html><head/><body><p><span style=\" font-size:12pt;\">The minimum number of consecuitve samples that must be above the threshold in order to register as an eyeblink onset.</span></p><p><span style=\" font-size:12pt;\">Higher values make the analysis less susceptible to noise</span></p></body></html>"))
        self.spinBox.setToolTip(_translate("Window", "How many standard deviations the threshold is away from the average"))
        self.spinBox.setWhatsThis(_translate("Window", "<html><head/><body><p><span style=\" font-size:12pt;\">The number of standard deviations away from the average that the sample must be in order to be above the eyeblink threshold</span></p></body></html>"))
        self.label_FileSettings.setText(_translate("Window", "File Settings"))
        self.label_Overwrite.setWhatsThis(_translate("Window", "<html><head/><body><p><span style=\" font-size:12pt;\">Replaces the current onset and offsest values of the file with the new ones. </span></p></body></html>"))
        self.label_Overwrite.setText(_translate("Window", "Overwrite Current File"))
        self.radioButton.setWhatsThis(_translate("Window", "<html><head/><body><p><span style=\" font-size:12pt;\">Replaces the current onset and offsest values of the file with the new ones. </span></p></body></html>"))
        self.label_GenerateNew.setWhatsThis(_translate("Window", "<html><head/><body><p><span style=\" font-size:12pt;\">Creates a copy of the current file with the new onset and offset values generated rather than overwriting the current one</span></p></body></html>"))
        self.label_GenerateNew.setText(_translate("Window", "Generate New File"))
        self.radioButton_2.setWhatsThis(_translate("Window", "<html><head/><body><p><span style=\" font-size:12pt;\">Creates a copy of the current file with the new onset and offset values generated rather than overwriting the current one</span></p></body></html>"))
        self.pushButton_ReAnalyze.setText(_translate("Window", "Re-Analyze"))
        self.pushButton_Cancel.setText(_translate("Window", "Cancel"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    displaySettingsWindow = QtWidgets.QDialog()
    ui = Ui_displaySettingsWindow()
    ui.setupUi(displaySettingsWindow)
    displaySettingsWindow.show()
    sys.exit(app.exec_())
