# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalysisSettingsUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_AnalysisSettings(object):
    def setupUi(self, Dialog_AnalysisSettings):
        Dialog_AnalysisSettings.setObjectName("Dialog_AnalysisSettings")
        Dialog_AnalysisSettings.resize(506, 198)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_AnalysisSettings.sizePolicy().hasHeightForWidth())
        Dialog_AnalysisSettings.setSizePolicy(sizePolicy)
        Dialog_AnalysisSettings.setSizeIncrement(QtCore.QSize(4, 4))
        Dialog_AnalysisSettings.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog_AnalysisSettings.setMouseTracking(False)
        Dialog_AnalysisSettings.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Dialog_AnalysisSettings.setSizeGripEnabled(False)
        Dialog_AnalysisSettings.setModal(False)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog_AnalysisSettings)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(10, 0, 0, 10)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.text_detail = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.text_detail.setFont(font)
        self.text_detail.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.text_detail.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.text_detail.setAcceptDrops(False)
        self.text_detail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_detail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_detail.setMidLineWidth(0)
        self.text_detail.setOverwriteMode(False)
        self.text_detail.setObjectName("text_detail")
        self.gridLayout.addWidget(self.text_detail, 0, 4, 2, 1, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 5)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 2, 0, 2, 5)
        self.pushButton_Cancel = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Cancel.sizePolicy().hasHeightForWidth())
        self.pushButton_Cancel.setSizePolicy(sizePolicy)
        self.pushButton_Cancel.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton_Cancel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.gridLayout.addWidget(self.pushButton_Cancel, 5, 3, 1, 2, QtCore.Qt.AlignHCenter)
        self.Label_MinSmpl = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Label_MinSmpl.setFont(font)
        self.Label_MinSmpl.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_MinSmpl.setWordWrap(True)
        self.Label_MinSmpl.setObjectName("Label_MinSmpl")
        self.gridLayout.addWidget(self.Label_MinSmpl, 1, 0, 1, 1)
        self.pushButton_Analyze = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Analyze.sizePolicy().hasHeightForWidth())
        self.pushButton_Analyze.setSizePolicy(sizePolicy)
        self.pushButton_Analyze.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton_Analyze.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Analyze.setObjectName("pushButton_Analyze")
        self.gridLayout.addWidget(self.pushButton_Analyze, 5, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.Label_StdDev = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_StdDev.sizePolicy().hasHeightForWidth())
        self.Label_StdDev.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Label_StdDev.setFont(font)
        self.Label_StdDev.setToolTipDuration(-1)
        self.Label_StdDev.setScaledContents(False)
        self.Label_StdDev.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_StdDev.setWordWrap(True)
        self.Label_StdDev.setObjectName("Label_StdDev")
        self.gridLayout.addWidget(self.Label_StdDev, 0, 0, 1, 1)
        self.spinBox_MinSmpl = QtWidgets.QSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_MinSmpl.sizePolicy().hasHeightForWidth())
        self.spinBox_MinSmpl.setSizePolicy(sizePolicy)
        self.spinBox_MinSmpl.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_MinSmpl.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBox_MinSmpl.setFont(font)
        self.spinBox_MinSmpl.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_MinSmpl.setSuffix("")
        self.spinBox_MinSmpl.setMinimum(1)
        self.spinBox_MinSmpl.setMaximum(500)
        self.spinBox_MinSmpl.setProperty("value", 1)
        self.spinBox_MinSmpl.setObjectName("spinBox_MinSmpl")
        self.gridLayout.addWidget(self.spinBox_MinSmpl, 1, 1, 1, 3)
        self.spinBox_StdDev = QtWidgets.QSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_StdDev.sizePolicy().hasHeightForWidth())
        self.spinBox_StdDev.setSizePolicy(sizePolicy)
        self.spinBox_StdDev.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_StdDev.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBox_StdDev.setFont(font)
        self.spinBox_StdDev.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_StdDev.setSuffix("")
        self.spinBox_StdDev.setMinimum(1)
        self.spinBox_StdDev.setMaximum(20)
        self.spinBox_StdDev.setProperty("value", 4)
        self.spinBox_StdDev.setObjectName("spinBox_StdDev")
        self.gridLayout.addWidget(self.spinBox_StdDev, 0, 1, 1, 3)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setRowStretch(0, 1)

        self.retranslateUi(Dialog_AnalysisSettings)
        self.pushButton_Cancel.clicked.connect(Dialog_AnalysisSettings.close)
        self.pushButton_Analyze.clicked.connect(Dialog_AnalysisSettings.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog_AnalysisSettings)
        Dialog_AnalysisSettings.setTabOrder(self.spinBox_StdDev, self.spinBox_MinSmpl)
        Dialog_AnalysisSettings.setTabOrder(self.spinBox_MinSmpl, self.text_detail)

    def retranslateUi(self, Dialog_AnalysisSettings):
        _translate = QtCore.QCoreApplication.translate
        Dialog_AnalysisSettings.setWindowTitle(_translate("Dialog_AnalysisSettings", "Analysis Settings"))
        self.text_detail.setPlaceholderText(_translate("Dialog_AnalysisSettings", "This area will display more detailed information about a selected setting."))
        self.pushButton_Cancel.setText(_translate("Dialog_AnalysisSettings", "Cancel"))
        self.Label_MinSmpl.setText(_translate("Dialog_AnalysisSettings", "Minimum Samples Required"))
        self.pushButton_Analyze.setText(_translate("Dialog_AnalysisSettings", "Re-Analyze"))
        self.Label_StdDev.setToolTip(_translate("Dialog_AnalysisSettings", "Number of Standard Deviations"))
        self.Label_StdDev.setStatusTip(_translate("Dialog_AnalysisSettings", "How many standard deviations away from the average the threshold for an eyeblink is"))
        self.Label_StdDev.setText(_translate("Dialog_AnalysisSettings", "Standard Deviations"))
