# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\colli\source\repos\NMOne\NMOne\DisplaySettingsUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_displaySettingsWindow(object):
    def setupUi(self, displaySettingsWindow):
        displaySettingsWindow.setObjectName("displaySettingsWindow")
        displaySettingsWindow.resize(758, 565)
        self.buttonBox = QtWidgets.QDialogButtonBox(displaySettingsWindow)
        self.buttonBox.setGeometry(QtCore.QRect(20, 510, 711, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(displaySettingsWindow)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 711, 471))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(50)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.displayRateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.displayRateLabel.setFont(font)
        self.displayRateLabel.setObjectName("displayRateLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.displayRateLabel)
        self.displayRateSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.displayRateSpinBox.setFont(font)
        self.displayRateSpinBox.setMaximum(120)
        self.displayRateSpinBox.setProperty("value", 10)
        self.displayRateSpinBox.setObjectName("displayRateSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.displayRateSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(50, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.antiAliasingLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.antiAliasingLabel.setFont(font)
        self.antiAliasingLabel.setObjectName("antiAliasingLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.antiAliasingLabel)
        self.antiAliasingComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.antiAliasingComboBox.setFont(font)
        self.antiAliasingComboBox.setObjectName("antiAliasingComboBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.antiAliasingComboBox)
        self.shadingLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.shadingLabel.setFont(font)
        self.shadingLabel.setObjectName("shadingLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.shadingLabel)
        self.shadingComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.shadingComboBox.setFont(font)
        self.shadingComboBox.setObjectName("shadingComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.shadingComboBox)
        self.backgroundColorLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.backgroundColorLabel.setFont(font)
        self.backgroundColorLabel.setObjectName("backgroundColorLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.backgroundColorLabel)
        spacerItem2 = QtWidgets.QSpacerItem(50, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.dataColorLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dataColorLabel.setFont(font)
        self.dataColorLabel.setObjectName("dataColorLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.dataColorLabel)
        self.backgroundColorButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.backgroundColorButton.setFont(font)
        self.backgroundColorButton.setText("")
        self.backgroundColorButton.setObjectName("backgroundColorButton")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.backgroundColorButton)
        self.dataColorButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dataColorButton.setFont(font)
        self.dataColorButton.setText("")
        self.dataColorButton.setObjectName("dataColorButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.dataColorButton)
        self.textColorLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textColorLabel.setFont(font)
        self.textColorLabel.setObjectName("textColorLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.textColorLabel)
        self.textColorButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textColorButton.setFont(font)
        self.textColorButton.setText("")
        self.textColorButton.setObjectName("textColorButton")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.textColorButton)
        self.stimulusColorLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stimulusColorLabel.setFont(font)
        self.stimulusColorLabel.setObjectName("stimulusColorLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.stimulusColorLabel)
        self.stimulusColorButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stimulusColorButton.setFont(font)
        self.stimulusColorButton.setText("")
        self.stimulusColorButton.setObjectName("stimulusColorButton")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.stimulusColorButton)
        self.axisColorLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.axisColorLabel.setFont(font)
        self.axisColorLabel.setObjectName("axisColorLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.axisColorLabel)
        self.axisColorButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.axisColorButton.setFont(font)
        self.axisColorButton.setText("")
        self.axisColorButton.setObjectName("axisColorButton")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.axisColorButton)
        self.displaySettingsLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.displaySettingsLabel.setFont(font)
        self.displaySettingsLabel.setObjectName("displaySettingsLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.displaySettingsLabel)

        self.retranslateUi(displaySettingsWindow)
        self.buttonBox.accepted.connect(displaySettingsWindow.accept)
        self.buttonBox.rejected.connect(displaySettingsWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(displaySettingsWindow)

    def retranslateUi(self, displaySettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        displaySettingsWindow.setWindowTitle(_translate("displaySettingsWindow", "Graph Display Settings"))
        self.displayRateLabel.setText(_translate("displaySettingsWindow", "Display Refresh Rate (Hz)"))
        self.antiAliasingLabel.setText(_translate("displaySettingsWindow", "Anti-Aliasing"))
        self.shadingLabel.setText(_translate("displaySettingsWindow", "Shade Area Under Curve"))
        self.backgroundColorLabel.setText(_translate("displaySettingsWindow", "Background Color"))
        self.dataColorLabel.setText(_translate("displaySettingsWindow", "Data Color"))
        self.textColorLabel.setText(_translate("displaySettingsWindow", "Text Color"))
        self.stimulusColorLabel.setText(_translate("displaySettingsWindow", "Stimulus Color"))
        self.axisColorLabel.setText(_translate("displaySettingsWindow", "Axis Color"))
        self.displaySettingsLabel.setText(_translate("displaySettingsWindow", "Graph Display Settings"))
