# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1560, 770)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rootHorizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.rootHorizontalLayout.setObjectName("rootHorizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(500, 16777215))
        self.scrollArea.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 481, 828))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout_2 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_2.setContentsMargins(10, 10, 0, 15)
        self.formLayout_2.setHorizontalSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.sessionSettings = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.sessionSettings.setFont(font)
        self.sessionSettings.setObjectName("sessionSettings")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sessionSettings)
        self.sessionName = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sessionName.setFont(font)
        self.sessionName.setObjectName("sessionName")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sessionName)
        self.sessionNameLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sessionNameLineEdit.sizePolicy().hasHeightForWidth())
        self.sessionNameLineEdit.setSizePolicy(sizePolicy)
        self.sessionNameLineEdit.setMinimumSize(QtCore.QSize(1, 0))
        self.sessionNameLineEdit.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sessionNameLineEdit.setFont(font)
        self.sessionNameLineEdit.setMaxLength(12)
        self.sessionNameLineEdit.setObjectName("sessionNameLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sessionNameLineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.subjectAgeLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.subjectAgeLabel.setFont(font)
        self.subjectAgeLabel.setObjectName("subjectAgeLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.subjectAgeLabel)
        self.subjectAgeSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subjectAgeSpinBox.sizePolicy().hasHeightForWidth())
        self.subjectAgeSpinBox.setSizePolicy(sizePolicy)
        self.subjectAgeSpinBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.subjectAgeSpinBox.setFont(font)
        self.subjectAgeSpinBox.setMaximum(1000)
        self.subjectAgeSpinBox.setProperty("value", 30)
        self.subjectAgeSpinBox.setObjectName("subjectAgeSpinBox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.subjectAgeSpinBox)
        self.subjectSexLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.subjectSexLabel.setFont(font)
        self.subjectSexLabel.setObjectName("subjectSexLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.subjectSexLabel)
        self.subjectSexComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subjectSexComboBox.sizePolicy().hasHeightForWidth())
        self.subjectSexComboBox.setSizePolicy(sizePolicy)
        self.subjectSexComboBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.subjectSexComboBox.setFont(font)
        self.subjectSexComboBox.setObjectName("subjectSexComboBox")
        self.subjectSexComboBox.addItem("")
        self.subjectSexComboBox.addItem("")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.subjectSexComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.sampleIntervalLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sampleIntervalLabel.setFont(font)
        self.sampleIntervalLabel.setObjectName("sampleIntervalLabel")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.sampleIntervalLabel)
        self.sampleIntervalSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.sampleIntervalSpinBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleIntervalSpinBox.sizePolicy().hasHeightForWidth())
        self.sampleIntervalSpinBox.setSizePolicy(sizePolicy)
        self.sampleIntervalSpinBox.setMinimumSize(QtCore.QSize(20, 0))
        self.sampleIntervalSpinBox.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sampleIntervalSpinBox.setFont(font)
        self.sampleIntervalSpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sampleIntervalSpinBox.setSuffix("")
        self.sampleIntervalSpinBox.setMinimum(1)
        self.sampleIntervalSpinBox.setMaximum(1000)
        self.sampleIntervalSpinBox.setProperty("value", 1)
        self.sampleIntervalSpinBox.setObjectName("sampleIntervalSpinBox")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.sampleIntervalSpinBox)
        self.trialCountLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trialCountLabel.setFont(font)
        self.trialCountLabel.setObjectName("trialCountLabel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.trialCountLabel)
        self.trialCountSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trialCountSpinBox.sizePolicy().hasHeightForWidth())
        self.trialCountSpinBox.setSizePolicy(sizePolicy)
        self.trialCountSpinBox.setMinimumSize(QtCore.QSize(125, 0))
        self.trialCountSpinBox.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trialCountSpinBox.setFont(font)
        self.trialCountSpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.trialCountSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.trialCountSpinBox.setSuffix("")
        self.trialCountSpinBox.setMinimum(1)
        self.trialCountSpinBox.setMaximum(1000)
        self.trialCountSpinBox.setSingleStep(1)
        self.trialCountSpinBox.setProperty("value", 20)
        self.trialCountSpinBox.setObjectName("trialCountSpinBox")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.trialCountSpinBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.itiLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.itiLabel.setFont(font)
        self.itiLabel.setObjectName("itiLabel")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.itiLabel)
        self.itiSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itiSpinBox.sizePolicy().hasHeightForWidth())
        self.itiSpinBox.setSizePolicy(sizePolicy)
        self.itiSpinBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.itiSpinBox.setFont(font)
        self.itiSpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.itiSpinBox.setSuffix("")
        self.itiSpinBox.setMaximum(10000)
        self.itiSpinBox.setProperty("value", 15)
        self.itiSpinBox.setObjectName("itiSpinBox")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.itiSpinBox)
        self.itiVarianceLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.itiVarianceLabel.setFont(font)
        self.itiVarianceLabel.setObjectName("itiVarianceLabel")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.itiVarianceLabel)
        self.itiVarianceSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itiVarianceSpinBox.sizePolicy().hasHeightForWidth())
        self.itiVarianceSpinBox.setSizePolicy(sizePolicy)
        self.itiVarianceSpinBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.itiVarianceSpinBox.setFont(font)
        self.itiVarianceSpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.itiVarianceSpinBox.setSuffix("")
        self.itiVarianceSpinBox.setMaximum(10000)
        self.itiVarianceSpinBox.setProperty("value", 3)
        self.itiVarianceSpinBox.setObjectName("itiVarianceSpinBox")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.itiVarianceSpinBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(12, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.thresholdSDLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.thresholdSDLabel.setFont(font)
        self.thresholdSDLabel.setObjectName("thresholdSDLabel")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.thresholdSDLabel)
        self.thresholdSDSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdSDSpinBox.sizePolicy().hasHeightForWidth())
        self.thresholdSDSpinBox.setSizePolicy(sizePolicy)
        self.thresholdSDSpinBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.thresholdSDSpinBox.setFont(font)
        self.thresholdSDSpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.thresholdSDSpinBox.setMinimum(1)
        self.thresholdSDSpinBox.setMaximum(20)
        self.thresholdSDSpinBox.setProperty("value", 4)
        self.thresholdSDSpinBox.setObjectName("thresholdSDSpinBox")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.thresholdSDSpinBox)
        self.thresholdMinDurLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.thresholdMinDurLabel.setFont(font)
        self.thresholdMinDurLabel.setObjectName("thresholdMinDurLabel")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.thresholdMinDurLabel)
        self.thresholdMinDurSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdMinDurSpinBox.sizePolicy().hasHeightForWidth())
        self.thresholdMinDurSpinBox.setSizePolicy(sizePolicy)
        self.thresholdMinDurSpinBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.thresholdMinDurSpinBox.setFont(font)
        self.thresholdMinDurSpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.thresholdMinDurSpinBox.setSuffix("")
        self.thresholdMinDurSpinBox.setMinimum(1)
        self.thresholdMinDurSpinBox.setMaximum(1000)
        self.thresholdMinDurSpinBox.setProperty("value", 10)
        self.thresholdMinDurSpinBox.setObjectName("thresholdMinDurSpinBox")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.thresholdMinDurSpinBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(16, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.trialSettings = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.trialSettings.setFont(font)
        self.trialSettings.setObjectName("trialSettings")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.trialSettings)
        self.trialDurationLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trialDurationLabel.setFont(font)
        self.trialDurationLabel.setObjectName("trialDurationLabel")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.trialDurationLabel)
        self.trialDurationSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trialDurationSpinBox.sizePolicy().hasHeightForWidth())
        self.trialDurationSpinBox.setSizePolicy(sizePolicy)
        self.trialDurationSpinBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trialDurationSpinBox.setFont(font)
        self.trialDurationSpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.trialDurationSpinBox.setSuffix("")
        self.trialDurationSpinBox.setMinimum(0)
        self.trialDurationSpinBox.setMaximum(30000)
        self.trialDurationSpinBox.setSingleStep(500)
        self.trialDurationSpinBox.setProperty("value", 3000)
        self.trialDurationSpinBox.setObjectName("trialDurationSpinBox")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.trialDurationSpinBox)
        self.baselineDurationLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.baselineDurationLabel.setFont(font)
        self.baselineDurationLabel.setObjectName("baselineDurationLabel")
        self.formLayout_2.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.baselineDurationLabel)
        self.baselineDurationSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baselineDurationSpinBox.sizePolicy().hasHeightForWidth())
        self.baselineDurationSpinBox.setSizePolicy(sizePolicy)
        self.baselineDurationSpinBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.baselineDurationSpinBox.setFont(font)
        self.baselineDurationSpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.baselineDurationSpinBox.setSuffix("")
        self.baselineDurationSpinBox.setMinimum(0)
        self.baselineDurationSpinBox.setMaximum(1000000)
        self.baselineDurationSpinBox.setSingleStep(500)
        self.baselineDurationSpinBox.setProperty("value", 1000)
        self.baselineDurationSpinBox.setObjectName("baselineDurationSpinBox")
        self.formLayout_2.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.baselineDurationSpinBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(20, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.csNameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.csNameLabel.setFont(font)
        self.csNameLabel.setObjectName("csNameLabel")
        self.formLayout_2.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.csNameLabel)
        self.csNameLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csNameLineEdit.sizePolicy().hasHeightForWidth())
        self.csNameLineEdit.setSizePolicy(sizePolicy)
        self.csNameLineEdit.setMinimumSize(QtCore.QSize(1, 0))
        self.csNameLineEdit.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.csNameLineEdit.setFont(font)
        self.csNameLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.csNameLineEdit.setText("")
        self.csNameLineEdit.setObjectName("csNameLineEdit")
        self.formLayout_2.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.csNameLineEdit)
        self.csDurationLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.csDurationLabel.setFont(font)
        self.csDurationLabel.setObjectName("csDurationLabel")
        self.formLayout_2.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.csDurationLabel)
        self.csDurationSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csDurationSpinBox.sizePolicy().hasHeightForWidth())
        self.csDurationSpinBox.setSizePolicy(sizePolicy)
        self.csDurationSpinBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.csDurationSpinBox.setFont(font)
        self.csDurationSpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.csDurationSpinBox.setSuffix("")
        self.csDurationSpinBox.setMinimum(0)
        self.csDurationSpinBox.setMaximum(10000)
        self.csDurationSpinBox.setSingleStep(100)
        self.csDurationSpinBox.setProperty("value", 100)
        self.csDurationSpinBox.setObjectName("csDurationSpinBox")
        self.formLayout_2.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.csDurationSpinBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(23, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        self.interstimulusIntervalLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.interstimulusIntervalLabel.setFont(font)
        self.interstimulusIntervalLabel.setObjectName("interstimulusIntervalLabel")
        self.formLayout_2.setWidget(24, QtWidgets.QFormLayout.LabelRole, self.interstimulusIntervalLabel)
        self.interstimulusIntervalSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interstimulusIntervalSpinBox.sizePolicy().hasHeightForWidth())
        self.interstimulusIntervalSpinBox.setSizePolicy(sizePolicy)
        self.interstimulusIntervalSpinBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.interstimulusIntervalSpinBox.setFont(font)
        self.interstimulusIntervalSpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.interstimulusIntervalSpinBox.setSuffix("")
        self.interstimulusIntervalSpinBox.setMaximum(1000000)
        self.interstimulusIntervalSpinBox.setSingleStep(100)
        self.interstimulusIntervalSpinBox.setProperty("value", 500)
        self.interstimulusIntervalSpinBox.setObjectName("interstimulusIntervalSpinBox")
        self.formLayout_2.setWidget(24, QtWidgets.QFormLayout.FieldRole, self.interstimulusIntervalSpinBox)
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(25, QtWidgets.QFormLayout.LabelRole, spacerItem7)
        self.usNameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.usNameLabel.setFont(font)
        self.usNameLabel.setObjectName("usNameLabel")
        self.formLayout_2.setWidget(26, QtWidgets.QFormLayout.LabelRole, self.usNameLabel)
        self.usNameLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usNameLineEdit.sizePolicy().hasHeightForWidth())
        self.usNameLineEdit.setSizePolicy(sizePolicy)
        self.usNameLineEdit.setMinimumSize(QtCore.QSize(1, 0))
        self.usNameLineEdit.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.usNameLineEdit.setFont(font)
        self.usNameLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.usNameLineEdit.setText("")
        self.usNameLineEdit.setObjectName("usNameLineEdit")
        self.formLayout_2.setWidget(26, QtWidgets.QFormLayout.FieldRole, self.usNameLineEdit)
        self.usDurationLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.usDurationLabel.setFont(font)
        self.usDurationLabel.setObjectName("usDurationLabel")
        self.formLayout_2.setWidget(27, QtWidgets.QFormLayout.LabelRole, self.usDurationLabel)
        self.usDurationSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usDurationSpinBox.sizePolicy().hasHeightForWidth())
        self.usDurationSpinBox.setSizePolicy(sizePolicy)
        self.usDurationSpinBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.usDurationSpinBox.setFont(font)
        self.usDurationSpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.usDurationSpinBox.setSuffix("")
        self.usDurationSpinBox.setMinimum(0)
        self.usDurationSpinBox.setMaximum(10000)
        self.usDurationSpinBox.setSingleStep(100)
        self.usDurationSpinBox.setProperty("value", 100)
        self.usDurationSpinBox.setObjectName("usDurationSpinBox")
        self.formLayout_2.setWidget(27, QtWidgets.QFormLayout.FieldRole, self.usDurationSpinBox)
        self.usDelayLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.usDelayLabel.setFont(font)
        self.usDelayLabel.setObjectName("usDelayLabel")
        self.formLayout_2.setWidget(28, QtWidgets.QFormLayout.LabelRole, self.usDelayLabel)
        self.usDelaySpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usDelaySpinBox.sizePolicy().hasHeightForWidth())
        self.usDelaySpinBox.setSizePolicy(sizePolicy)
        self.usDelaySpinBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.usDelaySpinBox.setFont(font)
        self.usDelaySpinBox.setMaximum(10000)
        self.usDelaySpinBox.setObjectName("usDelaySpinBox")
        self.formLayout_2.setWidget(28, QtWidgets.QFormLayout.FieldRole, self.usDelaySpinBox)
        self.minVoltageLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.minVoltageLabel.setFont(font)
        self.minVoltageLabel.setMouseTracking(False)
        self.minVoltageLabel.setObjectName("minVoltageLabel")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.minVoltageLabel)
        self.minVoltageSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minVoltageSpinBox.sizePolicy().hasHeightForWidth())
        self.minVoltageSpinBox.setSizePolicy(sizePolicy)
        self.minVoltageSpinBox.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.minVoltageSpinBox.setFont(font)
        self.minVoltageSpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.minVoltageSpinBox.setMaximum(7000)
        self.minVoltageSpinBox.setSingleStep(10)
        self.minVoltageSpinBox.setProperty("value", 500)
        self.minVoltageSpinBox.setObjectName("minVoltageSpinBox")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.minVoltageSpinBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.rootHorizontalLayout.addWidget(self.scrollArea)
        self.middleVerticalLine = QtWidgets.QFrame(self.centralwidget)
        self.middleVerticalLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.middleVerticalLine.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middleVerticalLine.setLineWidth(2)
        self.middleVerticalLine.setMidLineWidth(0)
        self.middleVerticalLine.setObjectName("middleVerticalLine")
        self.rootHorizontalLayout.addWidget(self.middleVerticalLine)
        self.rightSide = QtWidgets.QVBoxLayout()
        self.rightSide.setObjectName("rightSide")
        self.graphButtonLayout = QtWidgets.QHBoxLayout()
        self.graphButtonLayout.setObjectName("graphButtonLayout")
        self.lockButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lockButton.sizePolicy().hasHeightForWidth())
        self.lockButton.setSizePolicy(sizePolicy)
        self.lockButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/Unlocked Button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lockButton.setIcon(icon)
        self.lockButton.setIconSize(QtCore.QSize(100, 75))
        self.lockButton.setObjectName("lockButton")
        self.graphButtonLayout.addWidget(self.lockButton)
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/Play Button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon1)
        self.playButton.setIconSize(QtCore.QSize(100, 75))
        self.playButton.setObjectName("playButton")
        self.graphButtonLayout.addWidget(self.playButton)
        self.previousButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousButton.sizePolicy().hasHeightForWidth())
        self.previousButton.setSizePolicy(sizePolicy)
        self.previousButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.previousButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/Previous Button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon2)
        self.previousButton.setIconSize(QtCore.QSize(100, 95))
        self.previousButton.setObjectName("previousButton")
        self.graphButtonLayout.addWidget(self.previousButton)
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nextButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/Next Button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon3)
        self.nextButton.setIconSize(QtCore.QSize(100, 95))
        self.nextButton.setObjectName("nextButton")
        self.graphButtonLayout.addWidget(self.nextButton)
        spacerItem8 = QtWidgets.QSpacerItem(75, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.graphButtonLayout.addItem(spacerItem8)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.stopButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/Stop Button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon4)
        self.stopButton.setIconSize(QtCore.QSize(100, 75))
        self.stopButton.setObjectName("stopButton")
        self.graphButtonLayout.addWidget(self.stopButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.graphButtonLayout.addItem(spacerItem9)
        self.sessionInfoLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.sessionInfoLabel.setFont(font)
        self.sessionInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sessionInfoLabel.setObjectName("sessionInfoLabel")
        self.graphButtonLayout.addWidget(self.sessionInfoLabel)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.graphButtonLayout.addItem(spacerItem10)
        self.trialInfoLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.trialInfoLabel.setFont(font)
        self.trialInfoLabel.setText("")
        self.trialInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trialInfoLabel.setObjectName("trialInfoLabel")
        self.graphButtonLayout.addWidget(self.trialInfoLabel)
        spacerItem11 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.graphButtonLayout.addItem(spacerItem11)
        self.rightSide.addLayout(self.graphButtonLayout)
        self.horizontalLine = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLine.sizePolicy().hasHeightForWidth())
        self.horizontalLine.setSizePolicy(sizePolicy)
        self.horizontalLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontalLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontalLine.setObjectName("horizontalLine")
        self.rightSide.addWidget(self.horizontalLine)
        self.graphViewLayout = QtWidgets.QHBoxLayout()
        self.graphViewLayout.setObjectName("graphViewLayout")
        self.trialGraphWidget = GraphicsLayoutWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trialGraphWidget.sizePolicy().hasHeightForWidth())
        self.trialGraphWidget.setSizePolicy(sizePolicy)
        self.trialGraphWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.trialGraphWidget.setObjectName("trialGraphWidget")
        self.graphViewLayout.addWidget(self.trialGraphWidget)
        self.barGraphWidget = GraphicsLayoutWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barGraphWidget.sizePolicy().hasHeightForWidth())
        self.barGraphWidget.setSizePolicy(sizePolicy)
        self.barGraphWidget.setMinimumSize(QtCore.QSize(125, 0))
        self.barGraphWidget.setMaximumSize(QtCore.QSize(125, 16777215))
        self.barGraphWidget.setObjectName("barGraphWidget")
        self.graphViewLayout.addWidget(self.barGraphWidget)
        self.rightSide.addLayout(self.graphViewLayout)
        self.rootHorizontalLayout.addLayout(self.rightSide)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1560, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAnalyze = QtWidgets.QMenu(self.menubar)
        self.menuAnalyze.setObjectName("menuAnalyze")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionCaptureWindow = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionCaptureWindow.setFont(font)
        self.actionCaptureWindow.setObjectName("actionCaptureWindow")
        self.actionDisplaySettings = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionDisplaySettings.setFont(font)
        self.actionDisplaySettings.setObjectName("actionDisplaySettings")
        self.actionCaptureGraph = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionCaptureGraph.setFont(font)
        self.actionCaptureGraph.setObjectName("actionCaptureGraph")
        self.actionCaptureScreen = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionCaptureScreen.setFont(font)
        self.actionCaptureScreen.setObjectName("actionCaptureScreen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionNew.setFont(font)
        self.actionNew.setObjectName("actionNew")
        self.actionRe_Analyze_Session = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.actionRe_Analyze_Session.setFont(font)
        self.actionRe_Analyze_Session.setObjectName("actionRe_Analyze_Session")
        self.actionGenerate_Matrix_View = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionGenerate_Matrix_View.setFont(font)
        self.actionGenerate_Matrix_View.setObjectName("actionGenerate_Matrix_View")
        self.actionGoToTrial = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionGoToTrial.setFont(font)
        self.actionGoToTrial.setObjectName("actionGoToTrial")
        self.actionLoadParameters = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionLoadParameters.setFont(font)
        self.actionLoadParameters.setObjectName("actionLoadParameters")
        self.actionSaveParametersAs = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionSaveParametersAs.setFont(font)
        self.actionSaveParametersAs.setObjectName("actionSaveParametersAs")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveParametersAs)
        self.menuFile.addAction(self.actionLoadParameters)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCaptureGraph)
        self.menuFile.addAction(self.actionCaptureWindow)
        self.menuFile.addAction(self.actionCaptureScreen)
        self.menuEdit.addAction(self.actionDisplaySettings)
        self.menuAnalyze.addAction(self.actionRe_Analyze_Session)
        self.menuAnalyze.addAction(self.actionGenerate_Matrix_View)
        self.menuAnalyze.addSeparator()
        self.menuAnalyze.addAction(self.actionGoToTrial)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAnalyze.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.sessionNameLineEdit, self.subjectAgeSpinBox)
        MainWindow.setTabOrder(self.subjectAgeSpinBox, self.subjectSexComboBox)
        MainWindow.setTabOrder(self.subjectSexComboBox, self.sampleIntervalSpinBox)
        MainWindow.setTabOrder(self.sampleIntervalSpinBox, self.trialCountSpinBox)
        MainWindow.setTabOrder(self.trialCountSpinBox, self.itiSpinBox)
        MainWindow.setTabOrder(self.itiSpinBox, self.itiVarianceSpinBox)
        MainWindow.setTabOrder(self.itiVarianceSpinBox, self.thresholdSDSpinBox)
        MainWindow.setTabOrder(self.thresholdSDSpinBox, self.thresholdMinDurSpinBox)
        MainWindow.setTabOrder(self.thresholdMinDurSpinBox, self.trialDurationSpinBox)
        MainWindow.setTabOrder(self.trialDurationSpinBox, self.baselineDurationSpinBox)
        MainWindow.setTabOrder(self.baselineDurationSpinBox, self.csNameLineEdit)
        MainWindow.setTabOrder(self.csNameLineEdit, self.csDurationSpinBox)
        MainWindow.setTabOrder(self.csDurationSpinBox, self.interstimulusIntervalSpinBox)
        MainWindow.setTabOrder(self.interstimulusIntervalSpinBox, self.usNameLineEdit)
        MainWindow.setTabOrder(self.usNameLineEdit, self.usDurationSpinBox)
        MainWindow.setTabOrder(self.usDurationSpinBox, self.usDelaySpinBox)
        MainWindow.setTabOrder(self.usDelaySpinBox, self.lockButton)
        MainWindow.setTabOrder(self.lockButton, self.playButton)
        MainWindow.setTabOrder(self.playButton, self.scrollArea)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PiBlink"))
        self.sessionSettings.setText(_translate("MainWindow", "Session Parameters"))
        self.sessionName.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Prepended to beginning of file name for readability</span></p><p><span style=\" font-size:12pt;\">Max length of 12 characters</span></p><p><span style=\" font-size:12pt;\">May not contain any of the following characters: \\ / : * ? &quot; &lt; &gt; |</span></p></body></html>"))
        self.sessionName.setText(_translate("MainWindow", "Session Name"))
        self.sessionNameLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Prepended to beginning of file name for readability</span></p><p><span style=\" font-size:11pt;\">Max length of 12 characters</span></p><p><span style=\" font-size:11pt;\">May not contain any of the following characters: \\ / : * ? &quot; &lt; &gt; |</span></p></body></html>"))
        self.subjectAgeLabel.setText(_translate("MainWindow", "Subject Age (yr)"))
        self.subjectSexLabel.setText(_translate("MainWindow", "Subject Sex"))
        self.subjectSexComboBox.setItemText(0, _translate("MainWindow", "MALE"))
        self.subjectSexComboBox.setItemText(1, _translate("MainWindow", "FEMALE"))
        self.sampleIntervalLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The sample interval determines how often the signal is sampled. As the signal itself is updated 1000 times a second, it can be sampled as quickly as every millisecond.</span></p></body></html>"))
        self.sampleIntervalLabel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The sample interval determines how often the signal is sampled. As the signal itself is updated 1000 times a second, it can be sampled as quickly as every millisecond.</span></p></body></html>"))
        self.sampleIntervalLabel.setText(_translate("MainWindow", "Sample Interval (ms)"))
        self.sampleIntervalSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Time between each sample.</span></p><p><span style=\" font-size:10pt;\">A sample interval of 1 ms would generate 1000 samples per second.</span></p></body></html>"))
        self.sampleIntervalSpinBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The sample interval determines how often the signal is sampled. As the signal itself is updated 1000 times a second, it can be sampled as quickly as every millisecond.</span></p></body></html>"))
        self.trialCountLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The program will normally run the full number of trials and save the data acquired immediately upon each trial\'s completion. In cases where the data acquisition is stopped before the full number of trials have been completed, only the fully-finished trials will be kept, and the number of complete trials that is saved on the file will be updated to accurately reflect such.</span></p></body></html>"))
        self.trialCountLabel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The program will normally run the full number of trials and save the data acquired immediately upon each trial\'s completion. In cases where the data acquisition is stopped before the full number of trials have been completed, only the fully-finished trials will be kept, and the number of complete trials that is saved on the file will be updated to accurately reflect such.</span></p></body></html>"))
        self.trialCountLabel.setText(_translate("MainWindow", "Number of Trials"))
        self.trialCountSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Number of trials for this session</span></p></body></html>"))
        self.trialCountSpinBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The program will normally run the full number of trials and save the data acquired immediately upon each trial\'s completion. In cases where the data acquisition is stopped before the full number of trials have been completed, only the fully-finished trials will be kept, and the number of complete trials that is saved on the file will be updated to accurately reflect such.</span></p></body></html>"))
        self.itiLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This is the base value of the time between the end of one trial and the start of another. This base value is used with the ITI Variance value directly underneath it, such that the time between any two trials will be in a range of</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">[ interval - variance, interval + variance ]</span></p><p><span style=\" font-size:12pt;\">The program also checks for negative ITI values, so it will never have an ITI below zero.</span></p></body></html>"))
        self.itiLabel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This is the base value of the time between the end of one trial and the start of another. This base value is used with the ITI Variance value directly underneath it, such that the time between any two trials will be in a range of</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">[ interval - variance, interval + variance ]</span></p><p><span style=\" font-size:12pt;\">The program also checks for negative ITI values, so it will never have an ITI below zero.</span></p></body></html>"))
        self.itiLabel.setText(_translate("MainWindow", "Inter-trial Interval (s)"))
        self.itiSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Abbreviated as ITI</span></p></body></html>"))
        self.itiSpinBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This is the base value of the time between the end of one trial and the start of another. This base value is used with the ITI Variance value directly underneath it, such that the time between any two trials will be in a range of</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">[ interval - variance, interval + variance ]</span></p><p><span style=\" font-size:12pt;\">The program also checks for negative ITI values, so it will never have an ITI below zero.</span></p></body></html>"))
        self.itiVarianceLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The ITI Variance determines how far from the base ITI any one specific trial\'s ITI can be. </span></p></body></html>"))
        self.itiVarianceLabel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The ITI Variance determines how far from the base ITI any one specific trial\'s ITI can be. </span></p></body></html>"))
        self.itiVarianceLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">ITI Variance (s)</span></p></body></html>"))
        self.itiVarianceSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Random value from 0 to variance is added/subtracted to base duration each ITI</span></p></body></html>"))
        self.itiVarianceSpinBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The ITI Variance determines how far from the base ITI any one specific trial\'s ITI can be. </span></p></body></html>"))
        self.itiVarianceSpinBox.setPrefix(_translate("MainWindow", "± "))
        self.thresholdSDLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The program determines the threshold by calculating the average and standard deviation of the values recorded during the initial </span><span style=\" font-size:12pt;\">baseline</span><span style=\" font-size:12pt;\"> portion of the trial. The threshold is then set to be however many standard deviations specified away from the average.</span></p><p><span style=\" font-size:12pt;\">The threshold determines the minimum amplitude required for the signal to register as an eyeblink.</span></p></body></html>"))
        self.thresholdSDLabel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The program determines the threshold by calculating the average and standard deviation of the values recorded during the initial </span><span style=\" font-size:12pt;\">baseline</span><span style=\" font-size:12pt;\"> portion of the trial. The threshold is then set to be however many standard deviations specified away from the average.</span></p><p><span style=\" font-size:12pt;\">The threshold determines the minimum amplitude required for the signal to register as an eyeblink.</span></p></body></html>"))
        self.thresholdSDLabel.setText(_translate("MainWindow", "Threshold Std. Deviations"))
        self.thresholdSDSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">The number of standard deviations from the average the threshold is set to</span></p></body></html>"))
        self.thresholdSDSpinBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The program determines the threshold by calculating the average and standard deviation of the values recorded during the initial baseline portion of the trial. The threshold is then set to be however many standard deviations specified away from the average.</span></p><p><span style=\" font-size:12pt;\">The threshold determines the minimum amplitude required for the signal to register as an eyeblink.</span></p></body></html>"))
        self.thresholdMinDurLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This variable determines how long the signal must stay above the threshold in order for an eyeblink onset to be recorded. If the signal registers as an eyeblink, the program will record the </span><span style=\" font-size:12pt; font-weight:600;\">first</span><span style=\" font-size:12pt;\"> sample of the eyeblink that was above the threshold.</span></p><p><span style=\" font-size:12pt; font-weight:600;\">Example:</span></p><p><span style=\" font-size:12pt;\">I</span><span style=\" font-size:12pt;\">f samples 20 - 90 were above the threshold and the minimum duration were 10 ms, sample 20 would be marked as the onset, not sample 30.</span></p></body></html>"))
        self.thresholdMinDurLabel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This variable determines how long the signal must stay above the threshold in order for an eyeblink onset to be recorded. If the signal registers as an eyeblink, the program will record the </span><span style=\" font-size:12pt; font-weight:600;\">first</span><span style=\" font-size:12pt;\"> sample of the eyeblink that was above the threshold.</span></p><p><span style=\" font-size:12pt; font-weight:600;\">Example:</span></p><p><span style=\" font-size:12pt;\">I</span><span style=\" font-size:12pt;\">f samples 20 - 90 were above the threshold and the minimum duration were 10 ms, sample 20 would be marked as the onset, not sample 30.</span></p></body></html>"))
        self.thresholdMinDurLabel.setText(_translate("MainWindow", "Threshold Min. Duration (ms)"))
        self.thresholdMinDurSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">How long the signal must stay over the threshold to record an onset</span></p></body></html>"))
        self.thresholdMinDurSpinBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This variable determines how long the signal must stay above the threshold in order for an eyeblink onset to be recorded. If the signal registers as an eyeblink, the program will record the </span><span style=\" font-size:12pt; font-weight:600;\">first</span><span style=\" font-size:12pt;\"> sample of the eyeblink that was above the threshold.</span></p><p><span style=\" font-size:12pt; font-weight:600;\">Example:</span></p><p><span style=\" font-size:12pt;\">I</span><span style=\" font-size:12pt;\">f samples 20 - 90 were above the threshold and the minimum duration were 10 ms, sample 20 would be marked as the onset, not sample 30.</span></p></body></html>"))
        self.trialSettings.setText(_translate("MainWindow", "Trial Parameters"))
        self.trialDurationLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This is the total duration of the trial, including baseline, conditioned stimulus (CS), interstimulus interval, and unconditioned stimulus (US). The program will check before the settings are locked to ensure that the trial duration is sufficient given the other durations set.</span></p></body></html>"))
        self.trialDurationLabel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This is the total duration of the trial, including baseline, conditioned stimulus (CS), interstimulus interval, and unconditioned stimulus (US). The program will check before the settings are locked to ensure that the trial duration is sufficient given the other durations set.</span></p></body></html>"))
        self.trialDurationLabel.setText(_translate("MainWindow", "Trial Duration (ms)"))
        self.trialDurationSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Must be greater than or equal to baseline + CS + ISI + US</span></p></body></html>"))
        self.trialDurationSpinBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This is the total duration of the trial, including baseline, conditioned stimulus (CS), interstimulus interval, and unconditioned stimulus (US). The program will check before the settings are locked to ensure that the trial duration is sufficient given the other durations set.</span></p></body></html>"))
        self.baselineDurationLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This is the duration before the conditioned stimulus. The samples collected during this portion of the trial will be used to determine where the eyeblink threshold is for all other parts of the trial.</span></p></body></html>"))
        self.baselineDurationLabel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This is the duration before the conditioned stimulus. The samples collected during this portion of the trial will be used to determine where the eyeblink threshold is for all other parts of the trial.</span></p></body></html>"))
        self.baselineDurationLabel.setText(_translate("MainWindow", "Baseline Duration (ms)"))
        self.baselineDurationSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Duration before start of CS</span></p></body></html>"))
        self.baselineDurationSpinBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This is the duration before the conditioned stimulus. The samples collected during this portion of the trial will be used to determine where the eyeblink threshold is for all other parts of the trial.</span></p></body></html>"))
        self.csNameLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Conditioned Stimulus name</span></p></body></html>"))
        self.csNameLabel.setText(_translate("MainWindow", "CS Name"))
        self.csNameLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Conditioned Stimulus name</span></p></body></html>"))
        self.csNameLineEdit.setPlaceholderText(_translate("MainWindow", "Tone"))
        self.csDurationLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Conditioned Stimulus duration</span></p></body></html>"))
        self.csDurationLabel.setText(_translate("MainWindow", "CS Duration (ms)"))
        self.csDurationSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Conditioned Stimulus duration</span></p></body></html>"))
        self.interstimulusIntervalLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This is the time between the conditioned stimulus (CS) and unconditioned stimulus (US).</span></p></body></html>"))
        self.interstimulusIntervalLabel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This is the time between the conditioned stimulus (CS) and unconditioned stimulus (US).</span></p></body></html>"))
        self.interstimulusIntervalLabel.setText(_translate("MainWindow", "Interstimulus Interval (ms)"))
        self.interstimulusIntervalSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Abbreviated as ISI</span></p></body></html>"))
        self.interstimulusIntervalSpinBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">This is the time between the conditioned stimulus (CS) and unconditioned stimulus (US).</span></p></body></html>"))
        self.usNameLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Unconditioned Stimulus name</span></p></body></html>"))
        self.usNameLabel.setText(_translate("MainWindow", "US Name"))
        self.usNameLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Unconditioned Stimulus name</span></p></body></html>"))
        self.usNameLineEdit.setPlaceholderText(_translate("MainWindow", "Air Puff"))
        self.usDurationLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Unconditioned Stimulus duration</span></p></body></html>"))
        self.usDurationLabel.setText(_translate("MainWindow", "US Duration (ms)"))
        self.usDurationSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Unconditioned Stimulus duration</span></p></body></html>"))
        self.usDelayLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The US delay represents how long it takes for the actual, physical administering of the unconditioned stimulus after the signal has been sent. It thus represents how many milliseconds </span><span style=\" font-size:12pt; font-style:italic;\">before</span><span style=\" font-size:12pt;\"> the start of the US section that the signal will be sent to account for the delay.</span></p></body></html>"))
        self.usDelayLabel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The US delay represents how long it takes for the actual, physical administering of the unconditioned stimulus after the signal has been sent. It thus represents how many milliseconds </span><span style=\" font-size:12pt; font-style:italic;\">before</span><span style=\" font-size:12pt;\"> the start of the US section that the signal will be sent to account for the delay.</span></p></body></html>"))
        self.usDelayLabel.setText(_translate("MainWindow", "US Delay (ms)"))
        self.usDelaySpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Delay in ms from the time the signal is sent to the time the stimulus actually begins. The system compensates for this delay by sending the signal this amount of ms early so that it occurs on time.</span></p></body></html>"))
        self.usDelaySpinBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The US delay represents how long it takes for the actual, physical administering of the unconditioned stimulus after the signal has been sent. It thus represents how many milliseconds </span><span style=\" font-size:12pt; font-style:italic;\">before</span><span style=\" font-size:12pt;\"> the start of the US section that the signal will be sent to account for the delay.</span></p></body></html>"))
        self.minVoltageLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The range of the samples in a given trial must be greater than or equal to this value in order for the program to calculate onsets and offsets for the trial. Measured in millivolts.</span></p></body></html>"))
        self.minVoltageLabel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The range of the samples in a given trial must be greater than or equal to this value in order for the program to calculate onsets and offsets for the trial. Measured in millivolts.</span></p></body></html>"))
        self.minVoltageLabel.setText(_translate("MainWindow", "Min. Voltage Difference (mV)"))
        self.minVoltageSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">The range of the samples in a given trial must be greater than or equal to this value in order for the program to calculate onsets and offsets for the trial. Measured in millivolts.</span></p></body></html>"))
        self.minVoltageSpinBox.setWhatsThis(_translate("MainWindow", "The range of the samples in a given trial must be greater than or equal to this value in order for the program to calculate onsets and offsets for the trial. Measured in millivolts."))
        self.lockButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Locks and unlocks the settings. Settings must be locked before data acquisition can begin.</span></p><p><span style=\" font-size:11pt;\">When this button is pressed to lock the settings, the program runs through all of the settings to verify their validity. If any problem is detected, a notification will appear and the settings will not lock.</span></p></body></html>"))
        self.lockButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Locks and unlocks the settings. Settings must be locked before data acquisition can begin.</span></p><p><span style=\" font-size:11pt;\">When this button is pressed to lock the settings, the program runs through all of the settings to verify their validity. If any problem is detected, a notification will appear and the settings will not lock.</span></p></body></html>"))
        self.playButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Pause/Unpause data acquisition</span></p></body></html>"))
        self.playButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Plays/pauses the current session. This pauses data acquisition during trials and also pauses the countdown of the ITI when between trials. </span></p></body></html>"))
        self.previousButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Previous Trial</span></p></body></html>"))
        self.previousButton.setShortcut(_translate("MainWindow", "Left"))
        self.nextButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Next Trial</span></p></body></html>"))
        self.nextButton.setShortcut(_translate("MainWindow", "Right"))
        self.stopButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Stops and ends the current session. </span></p><p><span style=\" font-size:12pt;\">In </span><span style=\" font-size:12pt; font-weight:600;\">data acquisition mode</span><span style=\" font-size:12pt;\">, this will cause the program to save all completed trials in the current session before ending it. </span></p><p><span style=\" font-size:12pt;\">In </span><span style=\" font-size:12pt; font-weight:600;\">playback mode</span><span style=\" font-size:12pt;\">, this will simply end viewing of the opened session and return the program to acquisition mode, without altering any files.</span></p></body></html>"))
        self.stopButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Stops and ends the current session. </span></p><p><span style=\" font-size:12pt;\">In </span><span style=\" font-size:12pt; font-weight:600;\">data acquisition mode</span><span style=\" font-size:12pt;\">, this will cause the program to save all completed trials in the current session before closing ending it. </span></p><p><span style=\" font-size:12pt;\">In </span><span style=\" font-size:12pt; font-weight:600;\">playback mode</span><span style=\" font-size:12pt;\">, this will simply end viewing of the opened session and return the program to acquisition mode, without altering any files.</span></p></body></html>"))
        self.sessionInfoLabel.setText(_translate("MainWindow", "DATA ACQUISITION\n"
"\n"
""))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAnalyze.setTitle(_translate("MainWindow", "Analyze"))
        self.actionOpen.setText(_translate("MainWindow", "Open Session"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Select and open an existing session for playback"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionCaptureWindow.setText(_translate("MainWindow", "Capture Window"))
        self.actionCaptureWindow.setStatusTip(_translate("MainWindow", "Save a screenshot of the window"))
        self.actionCaptureWindow.setShortcut(_translate("MainWindow", "Ctrl+Shift+W"))
        self.actionDisplaySettings.setText(_translate("MainWindow", "Graph Settings"))
        self.actionDisplaySettings.setStatusTip(_translate("MainWindow", "Configure how the graph will appear"))
        self.actionDisplaySettings.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionCaptureGraph.setText(_translate("MainWindow", "Capture Graph"))
        self.actionCaptureGraph.setStatusTip(_translate("MainWindow", "Save a screenshot of the trial graph (excludes the volt meter)"))
        self.actionCaptureGraph.setShortcut(_translate("MainWindow", "Ctrl+Shift+G"))
        self.actionCaptureScreen.setText(_translate("MainWindow", "Capture Screen"))
        self.actionCaptureScreen.setStatusTip(_translate("MainWindow", "Save a screenshot of the entire screen"))
        self.actionCaptureScreen.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionNew.setText(_translate("MainWindow", "New Session"))
        self.actionNew.setStatusTip(_translate("MainWindow", "Create a new session in data acquisition mode"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionRe_Analyze_Session.setText(_translate("MainWindow", "Re-Analyze Session"))
        self.actionRe_Analyze_Session.setStatusTip(_translate("MainWindow", "Recalculate analysis of a session with different parameters"))
        self.actionRe_Analyze_Session.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionGenerate_Matrix_View.setText(_translate("MainWindow", "Generate Matrix View"))
        self.actionGenerate_Matrix_View.setStatusTip(_translate("MainWindow", "View multiple trials at once in a matrix"))
        self.actionGenerate_Matrix_View.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionGoToTrial.setText(_translate("MainWindow", "Go To Trial"))
        self.actionGoToTrial.setStatusTip(_translate("MainWindow", "Load a trial by specifying its number"))
        self.actionGoToTrial.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionLoadParameters.setText(_translate("MainWindow", "Load Parameters"))
        self.actionLoadParameters.setStatusTip(_translate("MainWindow", "Load in parameters from a parameter file"))
        self.actionLoadParameters.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionSaveParametersAs.setText(_translate("MainWindow", "Save Parameters"))
        self.actionSaveParametersAs.setStatusTip(_translate("MainWindow", "Save current parameters to a parameter file for future use"))
        self.actionSaveParametersAs.setShortcut(_translate("MainWindow", "Ctrl+S"))
from pyqtgraph import GraphicsLayoutWidget
