# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\colli\source\repos\CsCrMachineCode\MatrixParametersUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_trialMatrixParametersDialog(object):
    def setupUi(self, trialMatrixParametersDialog):
        trialMatrixParametersDialog.setObjectName("trialMatrixParametersDialog")
        trialMatrixParametersDialog.resize(447, 505)
        self.verticalLayout = QtWidgets.QVBoxLayout(trialMatrixParametersDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.trialMatrixParametersLabel = QtWidgets.QLabel(trialMatrixParametersDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trialMatrixParametersLabel.sizePolicy().hasHeightForWidth())
        self.trialMatrixParametersLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.trialMatrixParametersLabel.setFont(font)
        self.trialMatrixParametersLabel.setObjectName("trialMatrixParametersLabel")
        self.verticalLayout.addWidget(self.trialMatrixParametersLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.trialWidthSpinBox = QtWidgets.QSpinBox(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trialWidthSpinBox.setFont(font)
        self.trialWidthSpinBox.setMinimum(10)
        self.trialWidthSpinBox.setMaximum(10000)
        self.trialWidthSpinBox.setSingleStep(10)
        self.trialWidthSpinBox.setObjectName("trialWidthSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.trialWidthSpinBox)
        self.trialHeightLabel = QtWidgets.QLabel(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trialHeightLabel.setFont(font)
        self.trialHeightLabel.setObjectName("trialHeightLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.trialHeightLabel)
        self.trialHeightSpinBox = QtWidgets.QSpinBox(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trialHeightSpinBox.setFont(font)
        self.trialHeightSpinBox.setMinimum(10)
        self.trialHeightSpinBox.setMaximum(10000)
        self.trialHeightSpinBox.setSingleStep(10)
        self.trialHeightSpinBox.setObjectName("trialHeightSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.trialHeightSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.spacingLabel = QtWidgets.QLabel(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spacingLabel.setFont(font)
        self.spacingLabel.setObjectName("spacingLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.spacingLabel)
        self.spacingSpinBox = QtWidgets.QSpinBox(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spacingSpinBox.setFont(font)
        self.spacingSpinBox.setMaximum(500)
        self.spacingSpinBox.setProperty("value", 10)
        self.spacingSpinBox.setObjectName("spacingSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spacingSpinBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.maxRowsLabel = QtWidgets.QLabel(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.maxRowsLabel.setFont(font)
        self.maxRowsLabel.setObjectName("maxRowsLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.maxRowsLabel)
        self.maxRowsSpinBox = QtWidgets.QSpinBox(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.maxRowsSpinBox.setFont(font)
        self.maxRowsSpinBox.setMinimum(1)
        self.maxRowsSpinBox.setMaximum(1000)
        self.maxRowsSpinBox.setProperty("value", 100)
        self.maxRowsSpinBox.setObjectName("maxRowsSpinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.maxRowsSpinBox)
        self.maxColumnsLabel = QtWidgets.QLabel(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.maxColumnsLabel.setFont(font)
        self.maxColumnsLabel.setObjectName("maxColumnsLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.maxColumnsLabel)
        self.maxColumnsSpinBox = QtWidgets.QSpinBox(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.maxColumnsSpinBox.setFont(font)
        self.maxColumnsSpinBox.setMinimum(1)
        self.maxColumnsSpinBox.setMaximum(1000)
        self.maxColumnsSpinBox.setProperty("value", 100)
        self.maxColumnsSpinBox.setObjectName("maxColumnsSpinBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.maxColumnsSpinBox)
        self.trialWidthLabel = QtWidgets.QLabel(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trialWidthLabel.setFont(font)
        self.trialWidthLabel.setObjectName("trialWidthLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.trialWidthLabel)
        self.pageWidthLabel = QtWidgets.QLabel(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pageWidthLabel.setFont(font)
        self.pageWidthLabel.setObjectName("pageWidthLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pageWidthLabel)
        self.pageWidthSpinBox = QtWidgets.QSpinBox(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pageWidthSpinBox.setFont(font)
        self.pageWidthSpinBox.setMinimum(100)
        self.pageWidthSpinBox.setMaximum(10000)
        self.pageWidthSpinBox.setSingleStep(10)
        self.pageWidthSpinBox.setProperty("value", 1000)
        self.pageWidthSpinBox.setObjectName("pageWidthSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pageWidthSpinBox)
        self.pageHeightLabel = QtWidgets.QLabel(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pageHeightLabel.setFont(font)
        self.pageHeightLabel.setObjectName("pageHeightLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pageHeightLabel)
        self.pageHeightSpinBox = QtWidgets.QSpinBox(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pageHeightSpinBox.setFont(font)
        self.pageHeightSpinBox.setMinimum(100)
        self.pageHeightSpinBox.setMaximum(10000)
        self.pageHeightSpinBox.setSingleStep(10)
        self.pageHeightSpinBox.setProperty("value", 750)
        self.pageHeightSpinBox.setObjectName("pageHeightSpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pageHeightSpinBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalButtonLayout = QtWidgets.QHBoxLayout()
        self.horizontalButtonLayout.setObjectName("horizontalButtonLayout")
        self.cancelButton = QtWidgets.QPushButton(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalButtonLayout.addWidget(self.cancelButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalButtonLayout.addItem(spacerItem5)
        self.generateButton = QtWidgets.QPushButton(trialMatrixParametersDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.generateButton.setFont(font)
        self.generateButton.setObjectName("generateButton")
        self.horizontalButtonLayout.addWidget(self.generateButton)
        self.verticalLayout.addLayout(self.horizontalButtonLayout)

        self.retranslateUi(trialMatrixParametersDialog)
        QtCore.QMetaObject.connectSlotsByName(trialMatrixParametersDialog)
        trialMatrixParametersDialog.setTabOrder(self.trialWidthSpinBox, self.trialHeightSpinBox)
        trialMatrixParametersDialog.setTabOrder(self.trialHeightSpinBox, self.spacingSpinBox)
        trialMatrixParametersDialog.setTabOrder(self.spacingSpinBox, self.pageWidthSpinBox)
        trialMatrixParametersDialog.setTabOrder(self.pageWidthSpinBox, self.pageHeightSpinBox)
        trialMatrixParametersDialog.setTabOrder(self.pageHeightSpinBox, self.maxRowsSpinBox)
        trialMatrixParametersDialog.setTabOrder(self.maxRowsSpinBox, self.maxColumnsSpinBox)
        trialMatrixParametersDialog.setTabOrder(self.maxColumnsSpinBox, self.generateButton)
        trialMatrixParametersDialog.setTabOrder(self.generateButton, self.cancelButton)

    def retranslateUi(self, trialMatrixParametersDialog):
        _translate = QtCore.QCoreApplication.translate
        trialMatrixParametersDialog.setWindowTitle(_translate("trialMatrixParametersDialog", "Trial Matrix Parameters"))
        self.trialMatrixParametersLabel.setText(_translate("trialMatrixParametersDialog", "Trial Matrix Parameters"))
        self.trialHeightLabel.setText(_translate("trialMatrixParametersDialog", "Trial Height (px)"))
        self.spacingLabel.setToolTip(_translate("trialMatrixParametersDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Pixels of empty space between trials both horizontally and vertically. Spacing is only applied between trials, not on the edges.</span></p></body></html>"))
        self.spacingLabel.setText(_translate("trialMatrixParametersDialog", "Spacing (px)"))
        self.maxRowsLabel.setToolTip(_translate("trialMatrixParametersDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Once this limit is reached, a new page is made. A page is the set of all trials displayed on the screen at one time.</span></p></body></html>"))
        self.maxRowsLabel.setText(_translate("trialMatrixParametersDialog", "Max Rows Per Page"))
        self.maxColumnsLabel.setToolTip(_translate("trialMatrixParametersDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Trials and spacing will be added to each row until the max page width is reached, max columns per page is reached, or there are no more trials to display.</span></p></body></html>"))
        self.maxColumnsLabel.setText(_translate("trialMatrixParametersDialog", "Max Columns Per Page"))
        self.trialWidthLabel.setText(_translate("trialMatrixParametersDialog", "Trial Width (px)"))
        self.pageWidthLabel.setToolTip(_translate("trialMatrixParametersDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Trials and spacing will be added to each row until the max page width is reached, max columns per page is reached, or there are no more trials to display.</span></p></body></html>"))
        self.pageWidthLabel.setText(_translate("trialMatrixParametersDialog", "Max Page Width (px)"))
        self.pageHeightLabel.setToolTip(_translate("trialMatrixParametersDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Once this limit is reached, a new page is made. A page is the set of all trials displayed on the screen at one time.</span></p></body></html>"))
        self.pageHeightLabel.setText(_translate("trialMatrixParametersDialog", "Max Page Height (px)"))
        self.cancelButton.setText(_translate("trialMatrixParametersDialog", "Cancel"))
        self.generateButton.setText(_translate("trialMatrixParametersDialog", "Generate Matrix"))
        self.generateButton.setShortcut(_translate("trialMatrixParametersDialog", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trialMatrixParametersDialog = QtWidgets.QDialog()
    ui = Ui_trialMatrixParametersDialog()
    ui.setupUi(trialMatrixParametersDialog)
    trialMatrixParametersDialog.show()
    sys.exit(app.exec_())
