# -*- coding: utf-8 -*-
""" MatrixViewWindow.py
    Last Modified: 5/4/2020
    Taha Arshad, Tennessee Bonner, Devin Mensah Khalid Shaik, Collin Vaille

    This program sets up all of the UI in the Matrix View Window
"""
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_matrixViewDialog(object):
    def setupUi(self, matrixViewDialog):
        matrixViewDialog.setObjectName("matrixViewDialog")
        matrixViewDialog.resize(505, 204)
        self.verticalLayout = QtWidgets.QVBoxLayout(matrixViewDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.generalButtonsLayout = QtWidgets.QHBoxLayout()
        self.generalButtonsLayout.setObjectName("generalButtonsLayout")
        self.saveButton = QtWidgets.QPushButton(matrixViewDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.generalButtonsLayout.addWidget(self.saveButton)
        self.regenerateButton = QtWidgets.QPushButton(matrixViewDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.regenerateButton.setFont(font)
        self.regenerateButton.setObjectName("regenerateButton")
        self.generalButtonsLayout.addWidget(self.regenerateButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.generalButtonsLayout.addItem(spacerItem)
        self.closeButton = QtWidgets.QPushButton(matrixViewDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.generalButtonsLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.generalButtonsLayout)
        self.generalButtonsLine = QtWidgets.QFrame(matrixViewDialog)
        self.generalButtonsLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.generalButtonsLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.generalButtonsLine.setObjectName("generalButtonsLine")
        self.verticalLayout.addWidget(self.generalButtonsLine)
        self.horizontalLayoutAroundGrid = QtWidgets.QHBoxLayout()
        self.horizontalLayoutAroundGrid.setSpacing(0)
        self.horizontalLayoutAroundGrid.setObjectName("horizontalLayoutAroundGrid")
        self.gridWidget = QtWidgets.QWidget(matrixViewDialog)
        self.gridWidget.setObjectName("gridWidget")
        self.verticalLayoutAroundGrid = QtWidgets.QVBoxLayout(self.gridWidget)
        self.verticalLayoutAroundGrid.setObjectName("verticalLayoutAroundGrid")
        self.gridInfoLayout = QtWidgets.QHBoxLayout()
        self.gridInfoLayout.setObjectName("gridInfoLayout")
        self.trialNumbersLabel = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trialNumbersLabel.sizePolicy().hasHeightForWidth())
        self.trialNumbersLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trialNumbersLabel.setFont(font)
        self.trialNumbersLabel.setObjectName("trialNumbersLabel")
        self.gridInfoLayout.addWidget(self.trialNumbersLabel)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridInfoLayout.addItem(spacerItem1)
        self.sessionNameLabel = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sessionNameLabel.setFont(font)
        self.sessionNameLabel.setText("")
        self.sessionNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sessionNameLabel.setObjectName("sessionNameLabel")
        self.gridInfoLayout.addWidget(self.sessionNameLabel)
        self.verticalLayoutAroundGrid.addLayout(self.gridInfoLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayoutAroundGrid.addLayout(self.gridLayout)
        self.horizontalLayoutAroundGrid.addWidget(self.gridWidget)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutAroundGrid.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayoutAroundGrid)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.pageButtonsLine = QtWidgets.QFrame(matrixViewDialog)
        self.pageButtonsLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.pageButtonsLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pageButtonsLine.setObjectName("pageButtonsLine")
        self.verticalLayout.addWidget(self.pageButtonsLine)
        self.pageButtonsLayout = QtWidgets.QHBoxLayout()
        self.pageButtonsLayout.setObjectName("pageButtonsLayout")
        self.previousButton = QtWidgets.QPushButton(matrixViewDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.previousButton.setFont(font)
        self.previousButton.setObjectName("previousButton")
        self.pageButtonsLayout.addWidget(self.previousButton)
        self.pageNumberLabel = QtWidgets.QLabel(matrixViewDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pageNumberLabel.setFont(font)
        self.pageNumberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pageNumberLabel.setObjectName("pageNumberLabel")
        self.pageButtonsLayout.addWidget(self.pageNumberLabel)
        self.nextButton = QtWidgets.QPushButton(matrixViewDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.pageButtonsLayout.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.pageButtonsLayout)
        self.retranslateUi(matrixViewDialog)
        QtCore.QMetaObject.connectSlotsByName(matrixViewDialog)


    def retranslateUi(self, matrixViewDialog):
        _translate = QtCore.QCoreApplication.translate
        matrixViewDialog.setWindowTitle(_translate("matrixViewDialog", "Matrix View of Trials"))
        self.saveButton.setText(_translate("matrixViewDialog", "Save As Image"))
        self.regenerateButton.setText(_translate("matrixViewDialog", "Change Parameters"))
        self.closeButton.setText(_translate("matrixViewDialog", "Close"))
        self.trialNumbersLabel.setText(_translate("matrixViewDialog", "Loading..."))
        self.previousButton.setText(_translate("matrixViewDialog", "Previous Page"))
        self.previousButton.setShortcut(_translate("matrixViewDialog", "Left"))
        self.pageNumberLabel.setText(_translate("matrixViewDialog", "Page 1 / 1"))
        self.nextButton.setText(_translate("matrixViewDialog", "Next Page"))
        self.nextButton.setShortcut(_translate("matrixViewDialog", "Right"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    matrixViewDialog = QtWidgets.QDialog()
    ui = Ui_matrixViewDialog()
    ui.setupUi(matrixViewDialog)
    matrixViewDialog.show()
    sys.exit(app.exec_())
